spring:
  datasource:
    url: jdbc:mysql://http://43.142.90.238:3306/agilesoftware
    username: agilesoftware
    password: nxCHCcT8BY34aMzE
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 20235
# MyBatis 配置
mybatis:
  mapper-locations: classpath:mappers/*.xml